name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: checkout fmt
      uses: actions/checkout@v2
      with:
        repository: fmtlib/fmt
        path: fmt
    - name: install blaze
      shell: cmake -P {0}
      run: |
        file(DOWNLOAD "https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.8.tar.gz" ./blaze.zip SHOW_PROGRESS)
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./blaze.zip)
        execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${{ runner.workspace }}/blaze-build)
        execute_process(COMMAND ${CMAKE_COMMAND} 
            -S ${{ runner.workspace }}/blaze-3.8
            -B ${{ runner.workpsace }}/blade-build
            -D CMAKE_BUILD_TYPE=$BUILDTYPE
            -D CMAKE_INSTALL_PREFIX=${{ runner.workspace }}/third_party)
        execute_process(COMMAND ${CMAKE_COMMAND} --build ${{ runner.workspace }}/blaze-build)
        execute_process(COMMAND ${CMAKE_COMMAND} --install ${{ runner.workspace }}/blaze-build)
      working-directory: ${{ runner.workspace }}

    - name: create third party libraries install dir
      shell: bash
      run: cmake -E make_directory ${{ runner.workspace }}/third_party

    - name: debug github workspace directory
      shell: bash
      working-directory: ${{ github.workspace }}
      run: pwd; ls -l

    - name: create fmt build environment
      shell: bash
      run: cmake -E make_directory ${{ runner.workspace }}/fmt/build

    - name: Configure fmt cmake
      shell: bash
      working-directory: ${{ runner.workspace }}/fmt/build
      run: cmake ${{ github.workspace }}/fmt -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=${{ runner.workspace }}/third_party -DFMT_TEST=OFF

    - name: build fmt
      working-directory: ${{ runner.workspace }}/fmt/build
      run: cmake --build . && cmake --install .

#    - name: Create Build Environment
#      # Some projects don't allow in-source building, so create a separate build directory
#      # We'll use this as our working directory for all subsequent commands
#      run: cmake -E make_directory ${{runner.workspace}}/build
#
#    - name: Configure CMake
#      # Use a bash shell so we can use the same syntax for environment variable
#      # access regardless of the host operating system
#      shell: bash
#      working-directory: ${{runner.workspace}}/build
#      # Note the current convention is to use the -S and -B options here to specify source
#      # and build directories, but this is only available with CMake 3.13 and higher.
#      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
#      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
#
#    - name: Build
#      working-directory: ${{runner.workspace}}/build
#      shell: bash
#      # Execute the build.  You can specify a specific target with "--target <NAME>"
#      run: cmake --build . --config $BUILD_TYPE

    #- name: Test
    #  working-directory: ${{runner.workspace}}/build
    #  shell: bash
    #  # Execute tests defined by the CMake configuration.
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C $BUILD_TYPE
